apiVersion: v1
kind: Secret
metadata:
  name: backend-credentials
  namespace: todo-app
type: Opaque
data:
  # db_username: Cg==
  # db_password: Cg==
  # db_name: Cg==
  # db_host: Cg==
  # db_port: Cg==
  # secret: VGVzdAo=
  DATABASE_CONTACT_POINTS: bG9jYWxob3N0Cg==
  DATABASE_LOCAL_DATACENTER: dXMtZWFzdC0xCg==
  DATABASE_KEYSPACE: dG9kb2FwcAo=
  SECRET: MTIzNDUK
  DATABASE_USER: Cg==
  DATABASE_PASS: Cg==
