apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-traffic-between-namespaces
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "nodeapp.name" . }}
  - from:
    - labelSelector:
            matchExpressions:
            - key: scylla/datacenter
              operator: In
              values:
              - {{ .Values.networkPolicy.datacenter }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ template "nodeapp.name" . }}
  - to:
    - labelSelector:
            matchExpressions:
            - key: scylla/datacenter
              operator: In
              values:
              - {{ .Values.networkPolicy.datacenter }}              