{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-traffic-between-namespaces
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.todoNamespace }}
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.databaseNamespace }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.todoNamespace }}
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.databaseNamespace }}
{{- end -}}