additionalArguments:
# Configure your CertificateResolver here...

# Openstack DNS Challenge 
  - --certificatesresolvers.openstack.acme.dnschallenge=true
  - --certificatesresolvers.openstack.acme.dnschallenge.provider=openstack

logs:
# Configure log settings here...
  general:
    level: ERROR

ports:
# Configure your entrypoints here...
  web:
    # (optional) Permanent Redirect to HTTPS
    # redirectTo: websecure
  websecure:
    tls:
      enabled: false
      # (optional) Set a Default CertResolver
      certResolver: opemstack
  

env:
# Set your environment variables here...
# 
# DNS Challenge Credentials
# ---
# Openstack DNS Example:
  - name: OS_AUTH_URL
    valueFrom:
      secretKeyRef:
        key: OS_AUTH_URL
        name: openstack-credentials
  - name: OS_USERNAME
    valueFrom:
      secretKeyRef:
        key: OS_USERNAME
        name: openstack-credentials
  - name: OS_PASSWORD
    valueFrom:
      secretKeyRef:
        key: OS_PASSWORD
        name: openstack-credentials
  - name: OS_TENANT_NAME
    valueFrom:
      secretKeyRef:
        key: OS_TENANT_NAME
        name: openstack-credentials
  - name: OS_REGION_NAME
    valueFrom:
      secretKeyRef:
        key: OS_REGION_NAME
        name: openstack-credentials

# Disable Dashboard
ingressRoute:
  dashboard:
    enabled: true

# Persistent Storage
persistence:
  enabled: true
  name: ssl-certs
  size: 1Gi
  path: /ssl-certs

deployment:
  initContainers:
    # The "volume-permissions" init container is required if you run into permission issues.
    # Related issue: https://github.com/containous/traefik/issues/6972
    - name: volume-permissions
      image: busybox:1.31.1
      command: ["sh", "-c", "chmod -Rv 600 /ssl-certs/*"]
      volumeMounts:
        - name: ssl-certs
          mountPath: /ssl-certs

# Set Traefik as your default Ingress Controller, according to Kubernetes 1.19+ changes.
ingressClass:
  enabled: true
  isDefaultClass: true
