apps:
  name: todo-app
  nodeapp:
    name: todo-backend-app-deploy
    repository: jonathanschlitt/todo-backend
    tag: 'latest'
    replicaCount: 3
    # ressources for the backend pods
    cpuLimit: 1
    memoryLimit: 1Gi
    cpuRequest: 500m
    memoryRequest: 256Mi

  reactapp:
    name: todo-frontend-app-deploy
    repository: jonathanschlitt/todo-frontend
    tag: 'latest'
    replicaCount: 3
    backendUrl: 'http://todo-backend.k8s3.de' # set to loadbalancer ip of backend when not using ingress
    # ressources for the frontend pods
    cpuLimit: 1
    memoryLimit: 1Gi
    cpuRequest: 500m
    memoryRequest: 256Mi
  pullPolicy: Always

service:
  reactapp:
    name: todo-frontend-service
    portName: web
    ingressDomainName: 'todo-app-on-kubernetes.k8s3.de'
    type: LoadBalancer # Type ClusterIP for ingress
    protocol: TCP
    externalPort: 80
    internalPort: 8888

  nodeapp:
    name: todo-backend-service
    ingressDomainName: 'todo-backend.k8s3.de'
    type: LoadBalancer # Type ClusterIP for ingress
    protocol: TCP
    
    portName: web
    externalPort: 80
    internalPort: 7777

    metricsPortName: metrics
    externalMetricsPort: 9100
    internalMetricsPort: 9100

ingress:
  enabled: false

networkPolicy:
  todoNamespace: todo-app
  databaseNamespace: scylla
  datacenter: us-east-1
