apps:
  nodeapp:
    name: todo-backend-app-deploy
    repository: jonathanschlitt/todo-backend
    tag: 'latest'
    replicaCount: 3
  reactapp:
    name: todo-frontend-app-deploy
    repository: jonathanschlitt/todo-frontend
    tag: 'latest'
    replicaCount: 3
    backendUrl: "https://todo-backend.jonathanschlitt.cc"
  pullPolicy: Always

service:
  reactapp:
    name: todo-frontend-service
    ingressDomainName: "todo-app-on-kubernetes.jonathanschlitt.cc"
    type: ClusterIP
    protocol: TCP
    externalPort: 80
    internalPort: 8888
  nodeapp:
    name: todo-backend-service
    ingressDomainName: "todo-backend.jonathanschlitt.cc"
    type: ClusterIP
    protocol: TCP
    externalPort: 80
    internalPort: 7777
