apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.nodeapp.name }}
  namespace: todo-app
  labels:
    app: {{ template "nodeapp.name" . }}
    chart: {{ template "nodeapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.apps.nodeapp.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "nodeapp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nodeapp.name" . }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ template "nodeapp.name" . }}
            topologyKey: kubernetes.io/hostname
      containers:
      - image: {{ .Values.apps.nodeapp.repository }}:{{ .Values.apps.nodeapp.tag }}
        name: {{ .Chart.Name }}
      
        ports:
        - containerPort: {{ .Values.service.nodeapp.internalPort }}
        - containerPort: {{ .Values.service.nodeapp.externalMetricsPort }}
        imagePullPolicy: {{ .Values.apps.pullPolicy }}

        env:       
          - name: NODE_WORKER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName       
          - name: DATABASE_CONTACT_POINTS
            valueFrom:
              secretKeyRef:
                name: backend-credentials
                key:  DATABASE_CONTACT_POINTS
          - name: DATABASE_LOCAL_DATACENTER
            valueFrom:
              secretKeyRef:
                name: backend-credentials
                key:  DATABASE_LOCAL_DATACENTER
          - name: DATABASE_KEYSPACE
            valueFrom:
              secretKeyRef:
                name: backend-credentials
                key:  DATABASE_KEYSPACE
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: backend-credentials
                key:  SECRET
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: backend-credentials
                key:  DATABASE_USER
          - name: DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: backend-credentials
                key:  DATABASE_PASS
          - name: PORT
            value: {{ .Values.service.nodeapp.internalPort | quote }}
        resources:
          limits:
            cpu: {{ .Values.apps.nodeapp.cpuLimit }}
            memory: {{ .Values.apps.nodeapp.memoryLimit }}
          requests:
            cpu: {{ .Values.apps.nodeapp.cpuRequest }}
            memory: {{ .Values.apps.nodeapp.memoryRequest }}
    


       