apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.reactapp.name }}
  namespace: todo-app
  labels:
    app: {{ template "reactapp.name" . }}
    chart: {{ template "nodeapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.apps.reactapp.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "reactapp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "reactapp.name" . }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ template "reactapp.name" . }}
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: {{ .Values.apps.reactapp.repository }}:{{.Values.apps.reactapp.tag }}
        name: {{ .Chart.Name }}
        ports:
          - containerPort: {{ .Values.service.reactapp.internalPort }}
        imagePullPolicy: {{ .Values.apps.pullPolicy }}
        env:
        - name: REACT_APP_BACKEND_URL
          value: {{ .Values.apps.reactapp.backendUrl | quote }}
        - name: PRODUCTION_FRONTEND_PORT
          value: {{ .Values.service.reactapp.internalPort | quote }}
        - name: PORT
          value: {{ .Values.service.reactapp.internalPort | quote }}
        resources:
          limits:
            cpu: {{ .Values.apps.reactapp.cpuLimit }}
            memory: {{ .Values.apps.reactapp.memoryLimit }}
          requests:
            cpu: {{ .Values.apps.reactapp.cpuRequest }}
            memory: {{ .Values.apps.reactapp.memoryRequest }}

      

