apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.apps.name }}-metrics
spec:
  selector:
    matchLabels:
      app: nodeapp
  endpoints:
    - interval: 30s
      port: metrics
      path: /metrics
