apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: todoapp-frontend-pdb
  namespace: {{ .Release.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ template "reactapp.name" . }}
