name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Get latest version tag
      id: latest_tag
      run: |
        LATEST_TAG=$(docker run --rm -i jonathanschlitt/todo-backend:latest sh -c 'echo $VERSION')
        VERSION_ARRAY=(${LATEST_TAG//./ })
        MAJOR=${VERSION_ARRAY[0]}
        MINOR=${VERSION_ARRAY[1]}
        PATCH=$((${VERSION_ARRAY[2]}+1))
        echo "::set-output name=tag::$MAJOR.$MINOR.$PATCH"

    - name: Build the Docker image ==> Frontend
      working-directory: ./frontend
      run: |
        docker build . --build-arg VERSION=${{ steps.latest_tag.outputs.tag }} --tag jonathanschlitt/todo-frontend:latest
        docker tag jonathanschlitt/todo-frontend:latest jonathanschlitt/todo-frontend:${{ steps.latest_tag.outputs.tag }}
      
    - name: Build the Docker image ==> Backend
      working-directory: ./backend
      run: |
        docker build . --build-arg VERSION=${{ steps.latest_tag.outputs.tag }} --tag jonathanschlitt/todo-backend:latest
        docker tag jonathanschlitt/todo-backend:latest jonathanschlitt/todo-backend:${{ steps.latest_tag.outputs.tag }} 
      
    - name: Docker Push ==> Frontend
      run: |
        docker push jonathanschlitt/todo-frontend:${{ steps.latest_tag.outputs.tag }} 
      
    - name: Docker Push ==> Backend
      run: |
        docker push jonathanschlitt/todo-backend:${{ steps.latest_tag.outputs.tag }} 
